<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-09-17 10:33
=======
# Generated by Django 5.1.1 on 2024-09-09 17:19
>>>>>>> e3ea0c6fa9452c3434442e84407e82ab2df3ee54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
